version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5435:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=teste
      - POSTGRES_USER=teste
      - POSTGRES_DB=teste
